FROM            debian:latest

RUN             apt-get update -y && \
                mkdir /usr/bin/IronDome

COPY            ./IronDome      /usr/bin/IronDome/.
COPY            ./data          /usr/bin/IronDome/.